import type { Movie } from '../types/movie';
import type { MonetizationSettings } from '../types/monetization';

/**
 * High-quality fictional demo cinema archive items.
 * Uses royalty-free cinematic imagery and public creative commons demonstration streams.
 */
export const INITIAL_DEMO_MOVIES: Movie[] = [
  {
    id: 'kuro-m-001',
    title: 'SILHOUETTE OF THE RONIN',
    slug: 'silhouette-of-the-ronin',
    description: 'In an alternate neo-feudal Kyoto drenched in perpetual monsoons and neon static, an exiled master sword artisan navigates underworld syndicates to forge the blade that could sever the imperial surveillance grid.',
    poster_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=800&auto=format&fit=crop',
    backdrop_url: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?q=80&w=1920&auto=format&fit=crop',
    release_year: 2025,
    genre: 'Cyberpunk Noir',
    duration: '114 min',
    language: 'Japanese (Subtitled)',
    content_type: 'movie',
    source_type: 'uploaded',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    external_video_url: null,
    is_published: true,
    featured: true,
    director: 'Kenji Takahashi',
    created_at: '2026-01-15T10:00:00Z',
    updated_at: '2026-01-15T10:00:00Z',
    movie_links: {
      id: 'kuro-l-001',
      movie_id: 'kuro-m-001',
      step_1_url: 'https://example.com/monetag/link-step-1',
      step_2_url: 'https://example.com/monetag/link-step-2',
      step_3_url: 'https://example.com/monetag/link-step-3',
      final_url: null,
      final_destination_type: 'video_source',
    }
  },
  {
    id: 'kuro-m-002',
    title: 'THE MONOCHROME APERTURE',
    slug: 'the-monochrome-aperture',
    description: 'A reclusive darkroom archivist in 1974 Berlin discovers hidden micro-photographs inside an undeveloped reel of silver gelatin film, triggering a silent psychological chase across partitioned borders.',
    poster_url: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?q=80&w=800&auto=format&fit=crop',
    backdrop_url: 'https://images.unsplash.com/photo-1518676590629-3dcbd9c5a5c9?q=80&w=1920&auto=format&fit=crop',
    release_year: 2024,
    genre: 'Psychological Thriller',
    duration: '102 min',
    language: 'German / English',
    content_type: 'movie',
    source_type: 'external',
    video_url: null,
    external_video_url: 'https://www.youtube.com/watch?v=ScMzIvxBSi4',
    is_published: true,
    featured: false,
    director: 'Eleni Meyer',
    created_at: '2026-01-18T14:20:00Z',
    updated_at: '2026-01-18T14:20:00Z',
    movie_links: {
      id: 'kuro-l-002',
      movie_id: 'kuro-m-002',
      step_1_url: 'https://example.com/step1-verify',
      step_2_url: 'https://example.com/step2-sponsor',
      step_3_url: 'https://example.com/step3-direct',
      final_url: 'https://www.youtube.com/watch?v=ScMzIvxBSi4',
      final_destination_type: 'video_source',
    }
  },
  {
    id: 'kuro-m-003',
    title: 'ECHOES OF THE ABYSS',
    slug: 'echoes-of-the-abyss',
    description: 'Deep below the Mariana Trench in a pressurized geodesic research station, an oceanographer records acoustic signals that mimic the mathematical sequences of dead languages.',
    poster_url: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=800&auto=format&fit=crop',
    backdrop_url: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1920&auto=format&fit=crop',
    release_year: 2025,
    genre: 'Sci-Fi Mystery',
    duration: '128 min',
    language: 'English',
    content_type: 'movie',
    source_type: 'uploaded',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    external_video_url: null,
    is_published: true,
    featured: false,
    director: 'Dr. Marcus Vance',
    created_at: '2026-01-22T08:15:00Z',
    updated_at: '2026-01-22T08:15:00Z',
    movie_links: {
      id: 'kuro-l-003',
      movie_id: 'kuro-m-003',
      step_1_url: 'https://example.com/step1-monetag',
      step_2_url: 'https://example.com/step2-monetag',
      step_3_url: 'https://example.com/step3-monetag',
      final_url: null,
      final_destination_type: 'video_source',
    }
  },
  {
    id: 'kuro-m-004',
    title: 'SUMI-E: THE INK MASTER',
    slug: 'sumi-e-the-ink-master',
    description: 'A poetic documentary chronicling the final disciple of a 300-year-old pine soot ink guild in Nara, exploring how meditative brush strokes capture the transient spirit of Japanese aesthetics.',
    poster_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?q=80&w=800&auto=format&fit=crop',
    backdrop_url: 'https://images.unsplash.com/photo-1528164344705-475426879c0d?q=80&w=1920&auto=format&fit=crop',
    release_year: 2024,
    genre: 'Documentary',
    duration: '89 min',
    language: 'Japanese',
    content_type: 'movie',
    source_type: 'uploaded',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    external_video_url: null,
    is_published: true,
    featured: false,
    director: 'Aoi Murakami',
    created_at: '2026-01-28T19:40:00Z',
    updated_at: '2026-01-28T19:40:00Z',
    movie_links: {
      id: 'kuro-l-004',
      movie_id: 'kuro-m-004',
      step_1_url: 'https://example.com/step-1',
      step_2_url: 'https://example.com/step-2',
      step_3_url: 'https://example.com/step-3',
      final_url: null,
      final_destination_type: 'video_source',
    }
  },
  {
    id: 'kuro-m-005',
    title: 'KABUKICHO NOCTURNE',
    slug: 'kabukicho-nocturne',
    description: 'An insomnia-plagued street photographer documents the fleeting encounters between strangers in Shinjuku alleys, accidentally catching an art theft that implicates city officials.',
    poster_url: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?q=80&w=800&auto=format&fit=crop',
    backdrop_url: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?q=80&w=1920&auto=format&fit=crop',
    release_year: 2026,
    genre: 'Neo-Noir',
    duration: '110 min',
    language: 'Japanese / Korean',
    content_type: 'movie',
    source_type: 'external',
    video_url: null,
    external_video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    is_published: true,
    featured: false,
    director: 'Ren Matsubara',
    created_at: '2026-02-01T12:00:00Z',
    updated_at: '2026-02-01T12:00:00Z',
    movie_links: {
      id: 'kuro-l-005',
      movie_id: 'kuro-m-005',
      step_1_url: 'https://example.com/monetag-direct-1',
      step_2_url: 'https://example.com/monetag-direct-2',
      step_3_url: 'https://example.com/monetag-direct-3',
      final_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
      final_destination_type: 'video_source',
    }
  },
  {
    id: 'kuro-m-006',
    title: 'CHRONO: ZERO POINT',
    slug: 'chrono-zero-point',
    description: 'In 2099, when human consciousness can be serialized onto magnetic tape, a memory reclamation technician uncovers a deleted 3-second recording that could unravel civil society.',
    poster_url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?q=80&w=800&auto=format&fit=crop',
    backdrop_url: 'https://images.unsplash.com/photo-1511447333015-45b65e60f6d5?q=80&w=1920&auto=format&fit=crop',
    release_year: 2026,
    genre: 'Sci-Fi Mystery',
    duration: '95 min',
    language: 'English',
    content_type: 'movie',
    source_type: 'uploaded',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    external_video_url: null,
    is_published: false,
    featured: false,
    director: 'David Sterling',
    created_at: '2026-02-05T16:00:00Z',
    updated_at: '2026-02-05T16:00:00Z',
    movie_links: {
      id: 'kuro-l-006',
      movie_id: 'kuro-m-006',
      step_1_url: 'https://example.com/monetag/step-1',
      step_2_url: 'https://example.com/monetag/step-2',
      step_3_url: 'https://example.com/monetag/step-3',
      final_url: null,
      final_destination_type: 'video_source',
    }
  }
];

export const INITIAL_MONETIZATION_SETTINGS: MonetizationSettings = {
  id: 'global-monetization-001',
  provider_name: 'Monetag',
  enabled: true,
  step_1_url: 'https://example.com/monetag/smartlink-step-1',
  step_2_url: 'https://example.com/monetag/smartlink-step-2',
  step_3_url: 'https://example.com/monetag/smartlink-step-3',
  notes: 'Global default fallback links for Monetag SmartLink / Direct Link network. Applied if a movie does not specify individual step URLs.',
  updated_at: new Date().toISOString(),
};
